version: '3'

services:
  mysql:
    image: mysql:latest
    hostname: localhost_docker
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Passw0rd
      MYSQL_DATABASE: zed
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "33308:33308"
    volumes:
            - /db_scripts/docker-entrypoint-initdb.sql
            - db_data:/var/lib/mysql
  todos.api:
    image: ${DOCKER_REGISTRY-}todosapi
    build:
      context: .
      dockerfile: TodosMicroService/Dockerfile
    depends_on:
      - mysql
volumes:
    db_data:
